### ISSUE TITLE
Robot State Machine - Add file reception state

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#1055]
Add specific state to do file reception in order to avoid some of the bugs encountered

- [x] file reception must be in the global state machine
- [x] it must be accessible only when charging
- [x] it must be accessible only when battery is > *xx*%

Moved to #1189 

- ~[ ] it should show a file reception image indicating what is happening~
- ~[ ] it should show a file received "notification" when transfer is over~
- ~[ ] if the above images are not available, it must display a neutral face~

**Comment by YannLocatelli** [comment]
Related PR:

* #1067
