### ISSUE TITLE
Store BLE id/name for each robot when user changes it

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#1097]
see https://weareleka.slack.com/archives/C04F19WD6/p1644244822732459?thread_ts=1644243629.324549&cid=C04F19WD6

**Comment by YannLocatelli** [comment]
Related to #894

**Comment by YannLocatelli** [comment]
Related to 

- #1256

However, I don't think that a random name is necessary as default name. Current default name is fine (it's the serial number, short version)
