### ISSUE TITLE
[Task] - CoreLCDDriver - refactor to use CorePwm

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#1169]
## Description

Currently, CoreLCDDriver uses `mbed::PwmOut`.

It should be refactored to use our own `CorePwm` -- this would allow us to improve unit testing with mocks.

**Related epic/story/task**: 

## Subtasks 

- [ ] add `period` method to set the pwm period
- [ ] refactor CoreLCDDriver
- [ ] refactor tests

**Comment by YannLocatelli** [comment]
Done with #1365
