### ISSUE TITLE
Reinforcers occasionally don't turn off leds

### ISSUE THREAD

**Issue by HPezz** [leka/LekaOS#1226]
Occasionally,  function of an `animation->stop()` get called just right before a last call of `animation->run()`. This causes a turn off then a display of reinforcer that isn't turned off later. 

Temporarily fix with setting `_running = false` at the beginning of reinforcers animation stop().

This might be fix with refactor of EventLoopKit with no clear flags.

**Comment by ladislas** [comment]
fixed in 7ec349476b2f193ec13515ad0c2419b4e3e8f82a
