### ISSUE TITLE
[Task] - Audio Playback code architecture

### ISSUE THREAD

**Issue by SamHadjes** [leka/LekaOS#290]
## Description

Plan the code organization of the audio read feature

### Timer
- [ ] how to handle wav sampling rates (pre-defined standard values or on the fly calculation?)

### Other 
- [x] In this use case the DMA config is very specific (configurated by a DAC Hal function). Should we try to make a separate DMA class or do we keep it in a more _low level_ way
    > no need to make the DMA an external component if it is very specific
- [x] Do we need to implement a callback possibility for the timer (the DAC doesn't need one)?
   > implement the timer as a `DACTimer` so it is easily understood that it is configured to work with the DAC exclusively
- [x] Most of the low level setup is made in HAL_XXX_MspInit() overriden functions. Is it allowed/good practice in our case? This could be avoided by setting un a config macro which allows setting up manually the callbacks and skips the Msp calls.
    > Change the register callback defines in order to skip Msp function calls and integrate the low level initialization in the class methods

### Classes
```
CoreAudio
  public
  - initialize()
  - playFile(file name)
  - pause()
  - resume()
  - stop()
  - setVolume(volume)
  private
  - LKCoreHalBase &_hal
  - CoreDACBase &_dac
  - CoreDMABase &_dma
  - CoreBasicTimerBase &_timer
```
```
CoreBasicTimer implements CoreTimerBase
  public
  - initialize()
  - start(frequency/period)
  - stop()
  - setCallback(*cb)  (not needed in this use case but seems necessary to implement if the timer is generic)
  - connectToDAC()
  private
  - LKCoreHalBase &_hal
  - TIM_HandleTypeDef &_timer
```

```
CoreDAC implements CoreDACBase
  public
  - initialize()
  - linkDMA(CoreDMABase &dma)
  - setTrigger(TrigerType t)
  - write()  (not needed for audio playback but corresponds to typical use of a DAC)
  private
  - LKCoreHalBase &_hal
  - DAC_HandleTypeDef &_dac
```

```
CoreDMA implements CoreDMABase
  public
  - initialize()
  private
  - LKCoreHalBase &_hal
  - DMA_HandleTypeDef &_dma
```

**Comment by ladislas** [comment]
see #453
