### ISSUE TITLE
[Task] - Improvement possibilities for haptic actuator

### ISSUE THREAD

**Issue by SamHadjes** [leka/LekaOS#303]
# Summary of improvement possibilities for haptic actuator

### Audio
- [ ] - Non mono audio files
- [ ] - Handling of non standard .WAV headers 
- [ ] - Management of sampling rates lower than 1648Hz (108MHz/2^16)

### Vibrations
- [ ] - Multiple envelopes on same vib (to combine)
- [ ] - Other envelopes
- [ ] - Searching for an optimal frequency 
    - 90Hz seems ok, but generates dissonant noise
- [ ] - Sequence of varying vibrations with different parameters
    - different from a periodic call of the same vibration a given number of times

## Code
- [ ] - Unit tests
    - [ ] - CoreDACTimer unit tests (half done)
    - [ ] - CoreDAC unit tests (half done)
    - [ ] - CoreAudio unit tests
    - [ ] - WavReader unit tests
    - [ ] - WavFile unit tests
    - [ ] - CoreVibrations unit tests
- [ ] - clang-tidy
- [ ] - comment code
- [ ] - performance tests
    - [x] - vibration period calculation
    - [ ] - use of files instead of functions for envelopes
    - [ ] - use of CoreAudio and CoreVideo simultaneously
- [ ] - PR of all the code
    - [x] - CoreDACTimer
    - [x] - CoreDAC
    - [ ] - CoreAudio
    - [ ] - WavFile and WavReader
    - [ ] - CoreVibrations

**Comment by ladislas** [comment]
see #453
