### ISSUE TITLE
Previous Work - RFID, CoreRFID, RFIDKit, CR95HF

### ISSUE THREAD

**Issue by YannLocatelli** [leka/LekaOS#442]
## Description

Tasks done by Benjamin during his internship from March 2021 to August 2021.

The goal was to create CoreRFID and RFIDKit, plus the implementation for CoreRFID with CR95HF from ST.

His work was used for demos during Leka Launch Day and RFID Radio certification.

### Documents available

- [Flux diagram](https://www.dropbox.com/s/b1wbb3skzo6o94h/RFID_diagramme_de_flux.png?dl=0)
- [RFID Communication](https://www.dropbox.com/s/arq2l9bvobn4zz1/Communication%20RFID.pdf?dl=0)
- [Internship end summary](https://www.dropbox.com/s/zgzsnjjdn95qaxx/Benjamin-Roussilhe_Resume-de-fin-de-stage.pdf?dl=0)
- [CR95HF datasheet](https://www.dropbox.com/s/avhvvfdxdn2ccir/Aceltis-MF7-RFID-CR95HF.pdf?dl=0)

### PR and branches

- **CoreRFID** - Branch: [benjamin/feature/clean\_driver\_RFID](https://github.com/leka/LekaOS/tree/benjamin/feature/clean_driver_RFID) | PR: #272
- **RFIDKit** - Branch: [benjamin/feature/RFIDKit](https://github.com/leka/LekaOS/tree/benjamin/feature/RFIDKit) | PR: #274
- **Spike RFID** - Branch: [benjamin/feature/spike\_rfidkit](https://github.com/leka/LekaOS/tree/benjamin/feature/spike_rfidkit) | PR: N/A

Other related issue: #425

### CoreRFID #272

Can register a callback triggered by an serial input, a BufferedSerial modelize the UART communication between MCU and CR95HF RFID reader.

CR95HF should be calibrated before to be used. Here, the calibration is tag detection that will trigger the wake-up event of the reader. Benjamin did not succeed to use the procedure described in the datasheet but recommand the band value [0x70; 0x80]. If not correctly set, it can wakeup at any time.

CoreRFID is fully implemented and unit tested. There is no spike associated, because it gets hand in hand with RFIDKit.

### RFIDKit #274

Use CoreRFID #272.

RFIDKit use a switch state machine to go through the different stages to get data in tag explains in datasheet.

Anticollisions are not implemented.

CoreRFID is fully implemented, unit tested and run on robot. No spike on this PR, refer to branch [benjamin/feature/spike\_rfidkit](https://github.com/leka/LekaOS/tree/benjamin/feature/spike_rfidkit).

### Spike RFID

N/A

**Comment by ladislas** [comment]
closed by [556f8ab](https://github.com/leka/LekaOS/commit/556f8ab596a33f4935cf6dae4ca7160df8a408a5)
