### ISSUE TITLE
BLE - check MTU size ipad/robot

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#639]

**Comment by YannLocatelli** [comment]
You can check BLE exchanges with PacketLogger (presented on WWDC 2019) [[Link](https://developer.apple.com/videos/play/wwdc2019/901/)]

MTU proposed by iOS devices is 185, on robot side, it depend on mbed/cordio configuration. There is one for MTU desired, but another parameter set the reception buffer and that one also influence the negotiation of MTU.
```
        "rx-acl-buffer-size": {
            "help": "Size of the buffer holding the reassembled complete ACL packet. This will limit the effective ATT_MTU (to its value minus 4 bytes for the header). The size of the buffer must be small enough to be allocated from the existing cordio pool. If this value is increased you may need to adjust the memory pool.",
            "value": 70
```

[[Link](https://github.com/ARMmbed/mbed-os/blob/baf6a3022a328b91713e03fd88f65126a9a53f01/connectivity/FEATURE_BLE/source/cordio/mbed_lib.json#L54-L56)]

On robot side, the desired MTU cannot exceed 251.
