### ISSUE TITLE
BLE - Advertise battery % and display on iPad

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#642]

**Comment by YannLocatelli** [comment]
https://github.com/leka/LekaOS/pull/633

**Comment by YannLocatelli** [comment]
#736

**Comment by YannLocatelli** [comment]
Must be separated into 2 issues: one for the robot, one for the iPad.

The feature for the robot come along with #800 that is also linked to #662

**Comment by ladislas** [comment]
closed with 97fdaff92851caa5c111a0903717d3eeab8cfc78
