### ISSUE TITLE
Remove InvestigationDay lib and fix spikes depending on it

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#651]

**Comment by YannLocatelli** [comment]
https://github.com/leka/LekaOS/pull/652

**Comment by ladislas** [comment]
Remove those not needed

https://github.com/leka/LekaOS/blob/fb300498a796217a12482300543c47db4c29d104/libs/CMakeLists.txt#L26-L32

keep LekaTouch

**Comment by YannLocatelli** [comment]
If checked, the corresponding library can be removed

- [x] BLE (LKBLE)
- [x] ~~LekaBluetooth~~
- [x] LekaRFID
- [x] LekaScreen
- [ ] LekaTouch
- [x] LekaWifi
