### ISSUE TITLE
On OS start, if leds or motors are on, they are not stopped

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#671]

**Comment by YannLocatelli** [comment]
They are stopped at start of bootloader, should they also be stopped at start of OS?

**Comment by ladislas** [comment]
yes! the reason is that twice is better than one and when only working on the os (w/o the bootloader) I had the issue several time when flashing the robot while a reinforcer was happening.

this is fixed in c14e62029358e4cfb05fb553741aba7cf0796447 here

https://github.com/leka/LekaOS/commit/c14e62029358e4cfb05fb553741aba7cf0796447#diff-e8696ccb8a170e93094258caac435b9859546f72bec96507f38e6b2d67930faaR279-R281
