### ISSUE TITLE
Robots hang after random period of time

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#776]
After running a for an undefined period of time, the robot hangs while sleeping:

- if connected to BLE, connection is lost
- no output through serial (CoolTerm)
- no error messages
- charging the robot doesn't wake it up
- using emergency stop doesn't work

**Comment by YannLocatelli** [comment]
With the possibility of advertising end due to timeout, note that it is restart when it ends

https://github.com/leka/LekaOS/blob/9a6c22ce99d4fe800d384a952f4db85889c7d5dd/libs/BLEKit/source/CoreGapEventHandler.cpp#L40-L43

**Comment by ladislas** [comment]
moving to `Future releases` as we need to keep an eye on it.
