### ISSUE TITLE
Robots freeze when playing videos (edit)

### ISSUE THREAD

**Issue by HPezz** [leka/LekaOS#810]

**Comment by YannLocatelli** [comment]
Context of the freeze were on a PR with Screensaver. Please test the animation on validated code from develop by changing sleeping animation by singing animation and check if the freeze happens again.

**Comment by HPezz** [comment]
Bug recently seen with video "robot-emotion-happy-no_eyebrows" in Hugo's robot. A lead might be a file corruption because others videos work and it works on other robots.
