### ISSUE TITLE
BehaviorKit - Working - Fix neutral not the same as end of video

### ISSUE THREAD

**Issue by YannLocatelli** [leka/LekaOS#834]
See [Functional Tests](https://www.dropbox.com/scl/fi/6zyiksylr5w0lyp7guuls/2022_05_04-Checklist-V2.gsheet?dl=0&rlkey=ovcjb1rt4t15098m0su8rknms#gid=2007310270)

**Comment by ladislas** [comment]
Will be closed by #870
