### ISSUE TITLE
Discussion - Battery level representation

### ISSUE THREAD

**Issue by HPezz** [leka/LekaOS#864]
Which images can be played on the different battery level steps. 

Current implementation : 

- Less than <5% not charging -> Need Charge (robot go to charge)
- Less than 5% -> LowEnergy (empty red battery*)
- 5% - 25% -> Battery Low (One red bar)
- 25% - 50% -> Battery Medium (Two orange bars)
- 50% - 75 % -> Battery High (Three yellow or green bars)
- More than 75%  -> Battery Max (Four green bars)

New possible implementation 

- Less than 5% not charging -> To Charge (robot go to charge)
- Less than 25% -> LowEnergy (empty red battery*) 
- 25% - 50% -> Battery Low (One red bar)
- 50% - 75% -> Battery Medium (Two orange bars)
- 75% - 90 % -> Battery High (Three yellow or green bars)
- More than 90%  -> Battery Max (Four green bars)

**Comment by YannLocatelli** [comment]
And what is displayed between 0% and 5%?

**Comment by ladislas** [comment]
Adding here what I was saying there: https://github.com/leka/LekaOS/pull/870#discussion_r897353150

## Initial idea

### < 5 et < 25

![robot-battery-charging-empty_red](https://user-images.githubusercontent.com/2206544/173695463-546b3c55-2192-4663-b9fb-aab34e7a0491.jpg)

### < 50

![robot-battery-charging-quarter_1-red](https://user-images.githubusercontent.com/2206544/173695502-6eb144e5-02f7-4bcd-bb3a-4fa87c4ec371.jpg)

### < 75

![robot-battery-charging-quarter_2-orange](https://user-images.githubusercontent.com/2206544/173695532-8db63cc2-690c-4055-b24a-2e7410b134cc.jpg)

### < 90

![robot-battery-charging-quarter_3-green](https://user-images.githubusercontent.com/2206544/173695558-ebc228f1-cd04-4b8b-968b-87f7935be82d.jpg)

### > 90

![robot-battery-charging-quarter_4-green](https://user-images.githubusercontent.com/2206544/173695659-77b82be6-dd08-4410-82e1-fb2015329efe.jpg)

ou 

![robot-battery-charging-full_green](https://user-images.githubusercontent.com/2206544/173695682-53ce28e2-c6ab-4de4-9484-1c7259b8618f.jpg)

**Comment by ladislas** [comment]
## Alternative idea

### < 5 et < 25

![robot-battery-charging-empty_red](https://user-images.githubusercontent.com/2206544/173695463-546b3c55-2192-4663-b9fb-aab34e7a0491.jpg)

### < 50

![robot-battery-charging-quarter_1-red](https://user-images.githubusercontent.com/2206544/173695502-6eb144e5-02f7-4bcd-bb3a-4fa87c4ec371.jpg)

### < 75

![robot-battery-charging-quarter_2-orange](https://user-images.githubusercontent.com/2206544/173695532-8db63cc2-690c-4055-b24a-2e7410b134cc.jpg)

### < 85

![robot-battery-charging-quarter_3-green](https://user-images.githubusercontent.com/2206544/173695558-ebc228f1-cd04-4b8b-968b-87f7935be82d.jpg)

### < 95

![robot-battery-charging-quarter_4-green](https://user-images.githubusercontent.com/2206544/173695659-77b82be6-dd08-4410-82e1-fb2015329efe.jpg)

### > 95

![robot-battery-charging-full_green](https://user-images.githubusercontent.com/2206544/173695682-53ce28e2-c6ab-4de4-9484-1c7259b8618f.jpg)
