### ISSUE TITLE
FirmwareKit - Add format factory

### ISSUE THREAD

**Issue by YannLocatelli** [leka/LekaOS#904]
The factory os will be updated regularly, and shouldn't be too specific for each version.

Rename the factory os in SD even version is not clearly readable.

Warning: This will change the bootloader size and it shouldn't exceed end of its flash sector. If it happens, previous robot might have difficulties to update to new version since start of next sector might differ.

**Comment by ladislas** [comment]
check if `LekaOS-factory.bin` exists, if not, use `Leka0S-1.0.0`
