### ISSUE TITLE
SM & App - Add a "Go to Sleep" button

### ISSUE THREAD

**Issue by HPezz** [leka/LekaOS#924]
RECOMMENDED BY EXPERTS : Add a way to trigger sleep mode, making easier the end of an activity w/ Leka for the child.

**Comment by YannLocatelli** [comment]
Related to

- #1283

**Comment by YannLocatelli** [comment]
Discussed during Educational Development Retrospective of 23/02/2023 this topic is not a necessity for Educational Team.
